-- Replace <SECID_...> with real Dhan SecurityIds
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM-500>CE','DHAN','<SECID_BN_ATM_MINUS_500_CE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM-100>CE','DHAN','<SECID_BN_ATM_MINUS_100_CE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM>CE','DHAN','<SECID_BN_ATM_CE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM+100>CE','DHAN','<SECID_BN_ATM_PLUS_100_CE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM+500>CE','DHAN','<SECID_BN_ATM_PLUS_500_CE>','NFO');

INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM-500>PE','DHAN','<SECID_BN_ATM_MINUS_500_PE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM-100>PE','DHAN','<SECID_BN_ATM_MINUS_100_PE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM>PE','DHAN','<SECID_BN_ATM_PE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM+100>PE','DHAN','<SECID_BN_ATM_PLUS_100_PE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('BANKNIFTY24SEP<ATM+500>PE','DHAN','<SECID_BN_ATM_PLUS_500_PE>','NFO');

INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM-300>CE','DHAN','<SECID_NF_ATM_MINUS_300_CE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM-50>CE','DHAN','<SECID_NF_ATM_MINUS_50_CE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM>CE','DHAN','<SECID_NF_ATM_CE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM+50>CE','DHAN','<SECID_NF_ATM_PLUS_50_CE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM+300>CE','DHAN','<SECID_NF_ATM_PLUS_300_CE>','NFO');

INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM-300>PE','DHAN','<SECID_NF_ATM_MINUS_300_PE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM-50>PE','DHAN','<SECID_NF_ATM_MINUS_50_PE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM>PE','DHAN','<SECID_NF_ATM_PE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM+50>PE','DHAN','<SECID_NF_ATM_PLUS_50_PE>','NFO');
INSERT OR REPLACE INTO ltp_subscriptions VALUES('NIFTY24SEP<ATM+300>PE','DHAN','<SECID_NF_ATM_PLUS_300_PE>','NFO');
