name: docs
on:
  push:
    branches: [main]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate docs
        run: |
          python -m pip install --upgrade pip
          pip install pdoc python-dotenv
          python .\scripts\generate_docs.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs_md
  deploy:
    needs: build
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
